// Generated by CoffeeScript 1.6.3
(function() {
  var Delivery, Employee, Store, app, data, express, handlePOSMessage, http, io, receive, server, socketio;

  express = require('express');

  http = require('http');

  socketio = require('socket.io');

  app = express();

  app.configure(function() {
    app.use(express.bodyParser());
    return app.use(express["static"](__dirname + '/static'));
  });

  server = http.createServer(app);

  io = socketio.listen(server);

  io.set('log level', 1);

  server.listen(3001);

  app.post('/from-POS', function(req, res) {
    var message;
    message = req.body;
    handlePOSMessage(message);
    return res.end('success\n');
  });

  Store = (function() {
    function Store(storeID) {
      this.storeID = storeID;
      this.employees = {};
    }

    Store.prototype.addEmployee = function(employeeID) {
      return this.employees[employeeID] = new Employee(employeeID, this.storeID);
    };

    return Store;

  })();

  Employee = (function() {
    function Employee(employeeID, storeID) {
      this.employeeID = employeeID;
      this.storeID = storeID;
      this.deliveries = [];
      this.dispatched = false;
    }

    Employee.prototype._indexDelivery = function(checkNumber) {
      var d, index, res, _i, _len, _ref;
      res = -1;
      index = 0;
      _ref = this.deliveries;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        d = _ref[_i];
        if (d.checkNumber === checkNumber) {
          res = index;
        }
        index += 1;
      }
      return res;
    };

    Employee.prototype.addDelivery = function(delivery) {
      this.deliveries.push(delivery);
      return this.dispatched = new Date().getTime();
    };

    Employee.prototype.editDelivery = function(delivery) {
      var i;
      i = this._indexDelivery(delivery.checkNumber);
      return this.deliveries[i] = delivery;
    };

    Employee.prototype.removeDelivery = function(delivery) {
      var i;
      i = this._indexDelivery(delivery.checkNumber);
      this.deliveries.splice(i, 1);
      if (this.deliveries.length === 0) {
        return this.dispatched = false;
      }
    };

    return Employee;

  })();

  Delivery = (function() {
    function Delivery(jsonDelivery) {
      this.checkNumber = jsonDelivery.checkNumber;
      this.phoneNumber = jsonDelivery.phoneNumber;
      this.customerName = jsonDelivery.customerName;
      this.address1 = jsonDelivery.address1;
      this.address2 = jsonDelivery.address2;
      this.subDivision = jsonDelivery.subDivision;
      this.city = jsonDelivery.city;
      this.deliveryInstructions = jsonDelivery.deliveryInstructions;
      this.comments = jsonDelivery.comments;
      this.price = jsonDelivery.price;
      this.paymentType = jsonDelivery.paymentType;
      this.timePlaced = jsonDelivery.timePlaced;
      this.timeAssigned = new Date().getTime();
    }

    return Delivery;

  })();

  data = {
    stores: {},
    ensureStoreExists: function(storeID) {
      if (this.stores[storeID] == null) {
        return this.stores[storeID] = new Store(storeID);
      }
    },
    ensureEmployeeExists: function(storeID, employeeID) {
      var store;
      this.ensureStoreExists(storeID);
      store = this.stores[storeID];
      if (store.employees[employeeID] == null) {
        return store.addEmployee(employeeID);
      }
    }
  };

  handlePOSMessage = function(jsonMessage) {
    console.log("handlePOSMessage\n  messageType: " + jsonMessage.messageType + "\n  storeID: " + jsonMessage.storeID + "\n  employeeID: " + jsonMessage.employeeID + "\n  delivery: ");
    console.log(jsonMessage.delivery);
    return receive[jsonMessage.messageType](jsonMessage.storeID, jsonMessage.employeeID, new Delivery(jsonMessage.delivery));
  };

  receive = {
    assignDelivery: function(storeID, employeeID, delivery) {
      var employee;
      console.log("receive.assignDelivery");
      console.log("  storeID: " + storeID + "\n  employeeID: " + employeeID + "\n  delivery: ");
      console.log(delivery);
      data.ensureEmployeeExists(storeID, employeeID);
      employee = data.stores[storeID].employees[employeeID];
      employee.addDelivery(delivery);
      return io.sockets["in"](storeID + employeeID).emit('clientAssignDelivery', {
        "delivery": delivery,
        "dispatched": employee.dispatched
      });
    },
    unassignDelivery: function(storeID, employeeID, delivery) {
      var employee;
      console.log("receive.unassignDelivery");
      console.log("  storeID: " + storeID + "\n  employeeID: " + employeeID + "\n  delivery: ");
      console.log(delivery);
      data.ensureEmployeeExists(storeID, employeeID);
      employee = data.stores[storeID].employees[employeeID];
      employee.removeDelivery(delivery);
      return io.sockets["in"](storeID + employeeID).emit('clientUnassignDelivery', {
        "delivery": delivery,
        "dispatched": employee.dispatched
      });
    },
    editDelivery: function(storeID, employeeID, editedDelivery) {
      var employee;
      console.log("receive.editDelivery");
      console.log("  storeID: " + storeID + "\n  employeeID: " + employeeID + "\n  delivery: ");
      console.log(editedDelivery);
      data.ensureEmployeeExists(storeID, employeeID);
      employee = data.stores[storeID].employees[employeeID];
      employee.editDelivery(editedDelivery);
      return io.sockets["in"](storeID + employeeID).emit('clientEditDelivery', {
        "delivery": editedDelivery
      });
    }
  };

  io.sockets.on('connection', function(socket) {
    return socket.on('login', function(args) {
      var d, employee, _i, _len, _ref, _results;
      socket.join(args.storeID + args.employeeID);
      console.log("" + args.storeID + "'s employee, " + args.employeeID + " just logged in");
      data.ensureEmployeeExists(args.storeID, args.employeeID);
      employee = data.stores[args.storeID].employees[args.employeeID];
      _ref = employee.deliveries;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        d = _ref[_i];
        _results.push(socket.emit('clientAssignDelivery', {
          "delivery": d,
          "dispatched": employee.dispatched
        }));
      }
      return _results;
    });
  });

}).call(this);
